- hosts: all
  gather_facts: false
  tasks:
  - uri:
        url:              "{{ api_url }}{{api_job_path}}?name={{api_search}}"
        user:             "{{ user }}"
        password:         "{{ passwd }}"
        method:           GET
        status_code:      200
        force_basic_auth: true
        validate_certs:   false
    register:           api_results
    
 # - set_fact:
 #     api_url: "{{ api_url }}"
 #     api_job_path: "{{ api_job_path}}"
 #     api_search: "{{ api_search }}"
 #     user: "{{ user }}"
 #     passwd: "{{passwd }}"
 
  - set_fact:
      api_url: "api_url: {{ api_url }}"
      api_job_path: "api_job_path: {{ api_job_path}}"
      api_search: "api_search: {{ api_search }}"
      user: "user: {{ user }}"
      passwd: "passwd: {{passwd }}"
      
      
      
      
  - set_fact:
      ext_vars: "api_url + '\n' + api_job_path + '\n' + api_search + '\n' + user + '\n + passwd "
      temp_id:  "{{ (api_results.json.results | first)['id'] }}"      
  - uri:
      url:              "{{ api_url }}{{api_job_path}}/{{temp_id}}/launch/"
      user:             "{{ user }}"
      password:         "{{ passwd }}"
      method:           POST
      status_code:      201
      force_basic_auth: true
      validate_certs:   false
      body_format:      json
      body:
        extra_vars:     "{{ ext_vars }}"
      
