- hosts: all
  gather_facts: false
  tasks:
  - uri:
        url:              "{{ api_url }}{{api_job_path}}?name={{api_search}}"
        user:             "{{ user }}"
        password:         "{{ passwd }}"
        method:           GET
        status_code:      200
        force_basic_auth: true
        validate_certs:   false
    register:           api_results
    
  - set_fact:
      job_tempate_id: "{{ api_results.json.results | map(attribute='id') | first }}"
      extra_vars: "{{api_results.json.results  | map(attribute='extra_vars') | first | to_json }}"
      
  - uri:
        url:              "{{ api_url }}{{api_job_path}}/{{job_tempate_id}}/launch"
        user:             "{{ user }}"
        password:         "{{ passwd }}"
        method:           POST
        status_code:      201
        force_basic_auth: true
        validate_certs:   false      
        body:
          extra_vars: "{{extra_vars}}"
