- hosts: all
  gather_facts: false
  tasks:
  - uri:
        url:              "{{ api_url }}{{api_job_path}}?name={{api_search}}"
        user:             "{{ user }}"
        password:         "{{ passwd }}"
        method:           GET
        status_code:      200
        force_basic_auth: true
        validate_certs:   false
    register:           api_results
    

      
